room_topic:
  channel: app/room/{room}
  handler:
    callback: "room.topic"
  requirements:
    room:
      pattern: "[\\w]+"

pms_topic:
  channel: app/pms
  handler:
    callback: "pms.topic"

video_topic:
  channel: app/video/{room}
  handler:
    callback: "video.topic"
  requirements:
    room:
      pattern: "[\\w]+"
