api_login_check:
    path: /api/login_check

api_refresh_token:
    path:     /api/token_refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
