# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    encoder_json:
      class: Symfony\Component\Serializer\Encoder\JsonEncoder

    normalizer_object:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    serializer_json:
      class: Symfony\Component\Serializer\Serializer
      arguments:
        - ["@normalizer_object"]
        - ["@encoder_json"]
