# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    api.request_listener.class: AppBundle\EventListener\RequestListener
    api.controller_response_listener.class: AppBundle\EventListener\ControllerResponseListener
    api.exception_listener.class: AppBundle\EventListener\ExceptionListener

services:
    encoder_json:
      class: Symfony\Component\Serializer\Encoder\JsonEncoder

    normalizer_object:
      class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    serializer_json:
      class: Symfony\Component\Serializer\Serializer
      arguments:
        - ["@normalizer_object"]
        - ["@encoder_json"]

    ## ########################################################################
    ## Session
    ## ########################################################################
    app.session.handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\WriteCheckSessionHandler
        arguments:
            - "@snc_redis.session.handler"

    ## ########################################################################
    ## API Request Listener
    ## ########################################################################
    api.request_listener:
        class: "%api.request_listener.class%"
        arguments:
          - "@serializer_json"
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ## ########################################################################
    ## API Controller Response Listener
    ## ########################################################################
    api.controller_response_listener:
        class: "%api.controller_response_listener.class%"
        arguments:
          - "@serializer_json"
        tags:
          - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    ## ########################################################################
    ## API Exception Listener
    ## ########################################################################
    api.exception_listener:
        class: "%api.exception_listener.class%"
        arguments:
          - "@serializer_json"
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ## ########################################################################
    ## Websocket Parent Topic
    ## ########################################################################
    app.topic.parent:
        arguments:
          - "@service_container"
          - "@?monolog.logger.websocket"
        abstract: true
        private: true

    ## ########################################################################
    ## Websocket Auth Topic
    ## ########################################################################
    app.topic.auth:
        class: AppBundle\Topic\AuthTopic
        parent: app.topic.parent
        tags:
          - { name: gos_web_socket.topic }

    ## ########################################################################
    ## Websocket Room Topic
    ## ########################################################################
    app.topic.room:
        class: AppBundle\Topic\RoomTopic
        parent: app.topic.parent
        tags:
          - { name: gos_web_socket.topic }

    ## ########################################################################
    ## Websocket Video Topic
    ## ########################################################################
    app.topic.video:
        class: AppBundle\Topic\VideoTopic
        parent: app.topic.parent
        tags:
          - { name: gos_web_socket.topic }

    ## ########################################################################
    ## Video Periodic
    ## ########################################################################
    app.video.periodic:
      class: AppBundle\Periodic\VideoPeriodic
      tags:
        - { name: gos_web_socket.periodic }

    ## ########################################################################
    ## Websocket Authentication Provider
    ## ########################################################################
    gos_web_socket.websocket_authentification.provider:
        class: AppBundle\Auth\WebsocketAuthenticationProvider
        arguments:
            - "@security.token_storage"
            - "%gos_web_socket.firewall%"
            - "@gos_web_socket.client_storage"
            - "@lexik_jwt_authentication.security.guard.jwt_token_authenticator"
            - "@fos_user.user_provider.username"
            - "@?monolog.logger.websocket"
