services:
  ## ########################################################################
  ## Parent AbstractHandler
  ## ########################################################################
  admin.handler.parent:
    class: AdminBundle\Handler\AbstractHandler
    arguments:
      - "@doctrine"
      - "@service_container"

  ## ########################################################################
  ## User
  ## ########################################################################
  admin.handler.user:
    class: AdminBundle\Handler\UserHandler
    parent: admin.handler.parent

  ## ########################################################################
  ## Room
  ## ########################################################################
  admin.handler.room:
    class: AdminBundle\Handler\RoomHandler
    parent: admin.handler.parent
